[package]
name = "hierarchical_clustering"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.2"
csv = "1.2.1"
polars = "0.28.0"
